name: Deploy App and IAC to AWS

on:
  push:
    branches:
    - main

env:
  NODE_VERSION: 18
  TF_VERSION: 1.6.2

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.changes.outputs.app }}
      iac: ${{ steps.changes.outputs.iac }}
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app:
            - 'app/**'
          iac:
            - 'iac/**'  

  app:
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "hello app"

  iac:
    needs: changes
    if: ${{ needs.changes.outputs.iac == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: env.TF_VERSION
        terraform_wrapper: false

    - run: aws sts get-caller-identity 
    - run: terraform version




#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       - name: Terraform Apply
#         run: terraform apply tfplan -auto-approve